config/routes.rb
EhGol::Application.routes.draw do
  get "home", controller: 'static_pages'
  get "help", controller: 'static_pages'
  get "about", controller: 'static_pages'
  get 'match_brief', controller: 'static_pages'
  get 'match', controller: 'static_pages'

  resources :stages
  resources :teams
  resources :cities
  resources :matches
  
  resources :users
  match '/signup',  to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :comments, only: [:create, :destroy]

  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :label_colors, only: [:home, :match_brief, :match]

  def label_colors
    @LABEL_COLORS = {
      1 => "label-warning",
      2 => "label-success",
      3 => "label-important",
      4 => "label-info",
      5 => "",
      6 => "label-inverse"
    }
  end

  def home
    @matches = Match.all

    respond_to do |format|
      format.html
      format.json { render json: @matches,
        only: [:id, :date_and_time, :score_team1, :score_team2],
        include: {
          city: { only: [:name, :stadium, :latitude, :longitude] },
          stage: { only: [:name] },
          team1: { only: [:name, :code] },
          team2: { only: [:name, :code] }
        }
      }
    end
  end

  def match_brief
    @match = Match.find(params[:id])
    render partial: 'match_brief'
  end

  def match
    @match = Match.find(params[:id])
    @comments = Comment.find_all_by_match_id(params[:id])
    @comment = current_user.comments.build if signed_in?

    respond_to do |format|
      format.html
      format.json { render json: @match.comments,
        only: [:id, :content, :created_at],
        include: {
          user: { only: [:name] }
        }
      }
    end
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_details.html.erb
<div class="box box-match">
  <div class="match-teams">
    <div class="team1"><%= @match.team1.name ? @match.team1.name : @match.team1.code %></div>
    <div class="versus">×</div>
    <div class="team2"><%= @match.team2.name ? @match.team2.name : @match.team2.code %></div>
  </div>
  <div class="match-details">
    <p>Date: <%= @match.date_and_time %></p>
    <p>City: <%= @match.city.name %></p>
    <p>Place: <%= @match.city.stadium %> (<%= @match.city.stadium_alternative %>)</p>
    <p>Stage: <%= @match.stage.name %></p>
  </div>
</div>

<div class="match-map">
  <div class="match-map-google" id="match_map_google"></div>
  <div class="match-map-buttons">
    <div class="box">
      <div class="match-map-button-left"><%= link_to '<i class="icon-map-marker"></i> Open in Google Maps'.html_safe, "" %></div>
      <div class="match-map-button-right"><%= link_to '<i class="icon-road"></i> Get directions'.html_safe, "" %></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var mapOptions = {
    center: new google.maps.LatLng(<%= @match.city.latitude %>, <%= @match.city.longitude %>),
    zoom: 15,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("match_map_google"), mapOptions);
  var marker = new google.maps.Marker({
    position: mapOptions["center"],
    map: map,
    title: '<%= @match.city.stadium %> – <%= @match.city.name %>'
  });
</script>

app/views/static_pages/_match.html.erb
<div class="box box-match">
  <div class="match-details-date">
    <div class="match-details-date-month">
      <%= @match.date_and_time.strftime("%B") %>
    </div>
    <hr>
    <%= @match.date_and_time.day %>
    <div class="match-details-date-time">
      <i class="icon-time icon-white"></i> <%= @match.date_and_time.strftime('%H:%M') %>
    </div>
  </div>
  <div class="match-details">
    <p>City: <%= @match.city.name %></p>
    <p>Place: <%= @match.city.stadium %> (<%= @match.city.stadium_alternative %>)</p>
    <p><span class="label <%= @LABEL_COLORS[@match.stage.id] %>"><%= @match.stage.name %></span></p>
  </div>
  <div class="match-teams">
    <div class="team1"><%= @match.team1.name ? @match.team1.name : @match.team1.code %></div>
    <div class="versus">×</div>
    <div class="team2"><%= @match.team2.name ? @match.team2.name : @match.team2.code %></div>
    <div class="match-teams-button"><%= link_to "Click here to see more", "#" %></div>
  </div>
</div>

<div class="match-map">
  <div class="match-map-google" id="match_map_google"></div>
  <div class="match-map-buttons">
      <div class="box match-map-button-left">
        <i class="icon-map-marker"></i>
        <%= link_to 'Open in Google Maps'.html_safe, "http://maps.google.com/maps?ll=#{@match.city.latitude},#{@match.city.longitude}", target: "_blank" %>
      </div>
      <div class="box match-map-button-right">
        <i class="icon-road"></i>
        <%= link_to 'Get directions'.html_safe, "http://maps.google.com/maps?daddr=#{@match.city.latitude},#{@match.city.longitude}", target: "_blank" %>
      </div>
  </div>
</div>

<script type="text/javascript">
  var mapOptions = {
    center: new google.maps.LatLng(<%= @match.city.latitude %>, <%= @match.city.longitude %>),
    zoom: 15,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("match_map_google"), mapOptions);
  var marker = new google.maps.Marker({
    position: mapOptions["center"],
    map: map,
    title: '<%= @match.city.stadium %> – <%= @match.city.name %>'
  });
  $('.match-map-google').height($(window).height() - 375);
</script>

app/views/static_pages/_match_brief.html.erb
<div class="box box-match-brief">
  <div class="match-brief-details-date">
    <div class="match-brief-details-date-month">
      <%= @match.date_and_time.strftime("%B") %>
    </div>
    <hr>
    <%= @match.date_and_time.day %>
    <div class="match-brief-details-date-time">
      <i class="icon-time icon-white"></i> <%= @match.date_and_time.strftime('%H:%M') %>
    </div>
  </div>
  <div class="match-brief-details">
    <p>City: <%= @match.city.name %></p>
    <p>Place: <%= @match.city.stadium %> (<%= @match.city.stadium_alternative %>)</p>
    <p><span class="label <%= @LABEL_COLORS[@match.stage.id] %>"><%= @match.stage.name %></span></p>
  </div>
  <div class="match-brief-teams">
    <div class="team1"><%= @match.team1.name ? @match.team1.name : @match.team1.code %></div>
    <div class="versus">×</div>
    <div class="team2"><%= @match.team2.name ? @match.team2.name : @match.team2.code %></div>
    <div class="match-brief-teams-button"><%= link_to "Click here to see more", match_path(id: @match.id) %></div>
  </div>
</div>

<div class="match-map">
  <div class="match-map-google" id="match_map_google"></div>
  <div class="match-map-buttons">
      <div class="box match-map-button-left">
        <i class="icon-map-marker"></i>
        <%= link_to 'Open in Google Maps'.html_safe, "http://maps.google.com/maps?ll=#{@match.city.latitude},#{@match.city.longitude}", target: "_blank" %>
      </div>
      <div class="box match-map-button-right">
        <i class="icon-road"></i>
        <%= link_to 'Get directions'.html_safe, "http://maps.google.com/maps?daddr=#{@match.city.latitude},#{@match.city.longitude}", target: "_blank" %>
      </div>
  </div>
</div>

<script type="text/javascript">
  var mapOptions = {
    center: new google.maps.LatLng(<%= @match.city.latitude %>, <%= @match.city.longitude %>),
    zoom: 15,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("match_map_google"), mapOptions);
  var marker = new google.maps.Marker({
    position: mapOptions["center"],
    map: map,
    title: '<%= @match.city.stadium %> – <%= @match.city.name %>'
  });
  $('.match-map-google').height($(window).height() - 383);
</script>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="container-absolute-left">
  <% @matches.each do |match| %>
    <div class="box box-match-list">
      <div class="match-list-teams">
        <div class="team1"><%= match.team1.name ? match.team1.name : match.team1.code %></div>
        <div class="versus">×</div>
        <div class="team2"><%= match.team2.name ? match.team2.name : match.team2.code %></div>
      </div>
      <div class="match-list-details">
        <p>Date: <%= match.date_and_time %></p>
        <p>City: <%= match.city.name %></p>
        <p>Place: <%= match.city.stadium %></p>
        <p><span class="label <%= @LABEL_COLORS[match.stage.id] %>"><%= match.stage.name %></span></p>
      </div>
      <hr>
      <div class="match-list-buttons">
        <% message = "Hey, I'll be at #{match.city.stadium} in #{match.city.name} to watch the #{match.team1.name ? match.team1.name : match.team1.code} × #{match.team2.name ? match.team2.name : match.team2.code} match!" %>
        <% url = "#{root_url}#match_#{match.id}" %>
        <%= link_to image_tag('twitter.png', class: "match-list-button-share"), "http://twitter.com/intent/tweet?text=#{message}&url=#{url}", :target => "_blank" %>
        <%= link_to image_tag('facebook.png', class: "match-list-button-share"), "https://www.facebook.com/sharer/sharer.php?t=#{message}&u=#{url}", :target => "_blank" %>
        <%= link_to image_tag('gplus.png', class: "match-list-button-share"), "https://plus.google.com/share?url=#{url}", :target => "_blank" %>
        <%= link_to image_tag('expander.png', class: "match-list-button-expander", id: "match_#{match.id + 1}"), match_brief_path(id: match.id) %>
        <%= link_to image_tag('expander.png', class: "match-list-button-expander-phone visible-phone", id: "match_#{match.id + 1}"), match_path(id: match.id) %>
      </div>
    </div>
  <% end %>
</div>

<div class="container-fixed-right hidden-phone" id="match_brief" >
  <div class="box">
    <div class="box-content">
      <div class="welcome">
        <div class="title">
          Welcome to <span class="brand">É Gol</span> !
        </div>
        Here you'll be able to get through the World Cup knowing when, where,
        how and what is happening!
        <br /><br />
        <ul>
          <li>Easily share the matches you'll be watching.</li>
          <li>Sign up and post your own comments. Cheer for your team!</li>
          <li>Create your profile and mark your favorite matches.</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(window).on('load resize', function() {
    $('.match-map-google').height($(this).height() - 383);
    map.panTo(marker.getPosition());
  });
  $('.match-list-button-expander').click(function() {
    $.ajax({
      url: $(this).parent().attr('href'),
      success: function(html) {
        $('#match_brief').html(html);
      }
    });
    return false;
  });
</script>

app/views/static_pages/match.html.erb
<div class="box box-back">
  <%= link_to image_tag('expander-left-inv.png'), root_path %>
</div>

<div class="container-fixed-right" id="match_content" >
  <div class="box box-match-brief">
    <div class="match-brief-details-date">
      <div class="match-brief-details-date-month">
        <%= @match.date_and_time.strftime("%B") %>
      </div>
      <hr>
      <%= @match.date_and_time.day %>
      <div class="match-brief-details-date-time">
        <i class="icon-time icon-white"></i> <%= @match.date_and_time.strftime('%H:%M') %>
      </div>
    </div>
    <div class="match-brief-details">
      <p>City: <%= @match.city.name %></p>
      <p>Place: <%= @match.city.stadium %> (<%= @match.city.stadium_alternative %>)</p>
      <p><span class="label <%= @LABEL_COLORS[@match.stage.id] %>"><%= @match.stage.name %></span></p>
    </div>
    <div class="match-brief-teams">
      <div class="team1"><%= @match.team1.name ? @match.team1.name : @match.team1.code %></div>
      <div class="versus">×</div>
      <div class="team2"><%= @match.team2.name ? @match.team2.name : @match.team2.code %></div>
    </div>
  </div>

  <div class="match-map">
    <div class="match-map-google" id="match_map_google"></div>
    <div class="match-map-buttons">
        <div class="box match-map-button-left">
          <i class="icon-map-marker"></i>
          <%= link_to 'Open in Google Maps'.html_safe, "http://maps.google.com/maps?ll=#{@match.city.latitude},#{@match.city.longitude}", target: "_blank" %>
        </div>
        <div class="box match-map-button-right">
          <i class="icon-road"></i>
          <%= link_to 'Get directions'.html_safe, "http://maps.google.com/maps?daddr=#{@match.city.latitude},#{@match.city.longitude}", target: "_blank" %>
        </div>
    </div>
  </div>
</div>

<div class="container-absolute-left">
  <div class="box box-match-comment">
    <div class="match-comment-share">
      <% message = "Hey, I'll be at #{@match.city.stadium} in #{@match.city.name} to watch the #{@match.team1.name ? @match.team1.name : @match.team1.code} × #{@match.team2.name ? @match.team2.name : @match.team2.code} @match!" %>
      <% url = "#{root_url}#match_#{@match.id}" %>
      <%= link_to image_tag('twitter.png', class: "match-comment-share-button"), "http://twitter.com/intent/tweet?text=#{message}&url=#{url}", :target => "_blank" %>
      <%= link_to image_tag('facebook.png', class: "match-comment-share-button"), "https://www.facebook.com/sharer/sharer.php?t=#{message}&u=#{url}", :target => "_blank" %>
      <%= link_to image_tag('gplus.png', class: "match-comment-share-button"), "https://plus.google.com/share?url=#{url}", :target => "_blank" %>
    </div>
    <% if signed_in? %>
      <hr>
      <div class="box-comment-form">
        <%= form_for(@comment) do |f| %>
          <div class="input-append">
            <%= f.text_field :content, placeholder: "Compose your message..." %>
            <%= hidden_field :comment, :match_id, value: @match.id %>
            <%= f.submit "Post", class: "btn btn-primary comment-submit" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if @comments.empty? %>
    <div class="container-match-comment-empty">
      Be the first to leave a comment.
      <% if !signed_in? %>
        <br /><br />
        <%= link_to 'Sign up now!', signup_path %>
      <% end %>
    </div>
  <% end %>
  <div class="box-comments">
    <%= render partial: 'comments/comment', collection: @comments %>
  </div>
</div>

<script type="text/javascript">
  var mapOptions = {
    center: new google.maps.LatLng(<%= @match.city.latitude %>, <%= @match.city.longitude %>),
    zoom: 15,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("match_map_google"), mapOptions);
  var marker = new google.maps.Marker({
    position: mapOptions["center"],
    map: map,
    title: '<%= @match.city.stadium %> – <%= @match.city.name %>'
  });
  if (window.innerWidth > 767) $('.match-map-google').height($(window).height() - 383 + 34);
  $('#comment_content').width($('.box-comment-form').width() - 68);
  $(window).on('load resize', function() {
    if (window.innerWidth > 767) $('.match-map-google').height($(window).height() - 383 + 34);
    $('#comment_content').animate({ width: $('.box-comment-form').width() - 68 }, 50);
    map.panTo(marker.getPosition());
  });
  $('#new_comment').submit(function() {
    if ($('#comment_content').val() != "") {
      $.ajax({
        url: $(this).attr('action'),
        data: $(this).serialize(),
        type: 'post',
        success: function(html) {
          $('.container-match-comment-empty').fadeOut(150);
          $('.box-comments').fadeOut(150, function() {
            $(this).fadeIn(150).html(html);
          });
          $('#comment_content').val('');
        }
      });
    }
    return false;
  });
  $('.box-comments').on('click', '#delete_comment', function() {
    if (confirm('Are you sure?')) {
      var to_remove = $(this).parents('.box-comment');
      $.ajax({
        url: $(this).attr('href'),
        type: 'delete',
        success: function(html) {
          to_remove.hide(300, function() {
            $(this).remove();
          });
        }
      });
    }
    return false;
  });
</script>