config/routes.rb
EhGol::Application.routes.draw do
  get "home", controller: 'static_pages'
  get "help", controller: 'static_pages'
  get "about", controller: 'static_pages'
  get 'match_brief', controller: 'static_pages'
  get 'match', controller: 'static_pages'

  resources :stages
  resources :teams
  resources :cities
  resources :matches
  
  resources :users
  match '/signup',  to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :comments, only: [:create, :destroy]

  root to: 'static_pages#home'

end

app/models/stage.rb
class Stage < ActiveRecord::Base
  attr_accessible :name

  has_many :matches
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_filter :signed_in_user
  before_filter :admin_user

  def index
    @stages = Stage.all
  end

  def show
    @stage = Stage.find(params[:id])
  end

  def new
    @stage = Stage.new
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def create
    @stage = Stage.new(params[:stage])

    if @stage.save
      redirect_to @stage, notice: 'Stage was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @stage = Stage.find(params[:id])

    if @stage.update_attributes(params[:stage])
      redirect_to @stage, notice: 'Stage was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @stage = Stage.find(params[:id])
    @stage.destroy

    redirect_to stages_url
  end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_for(@stage) do |f| %>
  <% if @stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% @stage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing stage</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage, class: "btn btn-small" %>
<%= link_to 'Back', stages_path, class: "btn btn-small" %>

app/views/stages/index.html.erb
<h1>Listing stages</h1>

<br />

<%= link_to 'New Stage', new_stage_path, class: "btn btn-small" %>

<br />
<br />

<table class="table table-striped table-bordered table-condensed" >
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th></th>
  </tr>

<% @stages.each do |stage| %>
  <tr>
    <td><%= stage.id %></td>
    <td><%= stage.name %></td>
    <td><%= link_to 'Show', stage, class: "btn btn-small" %>
        <%= link_to 'Edit', edit_stage_path(stage), class: "btn btn-small" %>
        <%= link_to 'Destroy', stage, method: :delete, class: "btn btn-small", data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/stages/new.html.erb
<h1>New stage</h1>

<%= render 'form' %>

<%= link_to 'Back', stages_path, class: "btn btn-small" %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stage.name %>
</p>


<%= link_to 'Edit', edit_stage_path(@stage), class: "btn btn-small" %>
<%= link_to 'Back', stages_path, class: "btn btn-small" %>