config/routes.rb
EhGol::Application.routes.draw do
  get "home", controller: 'static_pages'
  get "help", controller: 'static_pages'
  get "about", controller: 'static_pages'
  get 'match_brief', controller: 'static_pages'
  get 'match', controller: 'static_pages'

  resources :stages
  resources :teams
  resources :cities
  resources :matches
  
  resources :users
  match '/signup',  to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :comments, only: [:create, :destroy]

  root to: 'static_pages#home'

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :date_and_time, :score_team1, :score_team2, :stage_id, :city_id, :team1_id, :team2_id

  belongs_to :city
  belongs_to :stage
  belongs_to :team1, class_name: 'Team', foreign_key: 'team1_id'
  belongs_to :team2, class_name: 'Team', foreign_key: 'team2_id'

  has_many :comments
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :signed_in_user
  before_filter :admin_user

  def index
    @matches = Match.all
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new
  end

  def edit
    @match = Match.find(params[:id])
  end

  def create
    @match = Match.new(params[:match])

    if @match.save
      redirect_to @match, notice: 'Match was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @match = Match.find(params[:id])

    if @match.update_attributes(params[:match])
      redirect_to @match, notice: 'Match was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    redirect_to matches_url
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_and_time %>
    <%= f.text_field :date_and_time %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.collection_select :city_id, City.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :team1 %>
    <%= f.collection_select :team1_id, Team.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :team2 %>
    <%= f.collection_select :team2_id, Team.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :score_team1 %>
    <%= f.text_field :score_team1 %>
  </div>
  <div class="field">
    <%= f.label :score_team2 %>
    <%= f.text_field :score_team2 %>
  </div>
  <div class="field" >
    <%= f.label :stage %>
    <%= f.collection_select :stage_id, Stage.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match, class: "btn btn-small" %>
<%= link_to 'Back', matches_path, class: "btn btn-small" %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<br />

<%= link_to 'New Match', new_match_path, class: "btn btn-small" %>

<br />
<br />

<table class="table table-striped table-bordered table-condensed" >
  <tr>
    <th>ID</th>
    <th>Date/Time</th>
    <th>Score_Team1</th>
    <th>Score_Team2</th>
    <th>City ID</th>
    <th>Team1 ID</th>
    <th>Team2 ID</th>
    <th>Stage ID</th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.id %></td>
    <td><%= match.date_and_time %></td>
    <td><%= match.score_team1 %></td>
    <td><%= match.score_team2 %></td>
    <td><%= match.city.id %> (<%= match.city.name %>)</td>
    <td><%= match.team1.id %> (<%= match.team1.code %>) <i><%= match.team1.name %></i></td>
    <td><%= match.team2.id %> (<%= match.team2.code %>) <i><%= match.team2.name %></i></td>
    <td><%= match.stage.id %> (<%= match.stage.name %>)</td>
    <td><%= link_to 'Show', match, class: "btn btn-small" %>
        <%= link_to 'Edit', edit_match_path(match), class: "btn btn-small" %>
        <%= link_to 'Destroy', match, class: "btn btn-small", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path, class: "btn btn-small" %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date/Time:</b>
  <%= @match.date_and_time %>
</p>

<p>
  <b>City:</b>
  <%= @match.city.name %>
</p>

<p>
  <b>Team1:</b>
  <%= @match.team1.name %>
</p>

<p>
  <b>Team2:</b>
  <%= @match.team2.name %>
</p>

<p>
  <b>Score_Team1:</b>
  <%= @match.score_team1 %>
</p>

<p>
  <b>Score_Team2:</b>
  <%= @match.score_team2 %>
</p>

<p>
  <b>Stage:</b>
  <%= @match.stage.name %>
</p>


<%= link_to 'Edit', edit_match_path(@match), class: "btn btn-small" %>
<%= link_to 'Back', matches_path, class: "btn btn-small" %>