config/routes.rb
EhGol::Application.routes.draw do
  get "home", controller: 'static_pages'
  get "help", controller: 'static_pages'
  get "about", controller: 'static_pages'
  get 'match_brief', controller: 'static_pages'
  get 'match', controller: 'static_pages'

  resources :stages
  resources :teams
  resources :cities
  resources :matches
  
  resources :users
  match '/signup',  to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :comments, only: [:create, :destroy]

  root to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<hr>

<% if !current_page?(root_path) %>
  <div class="row">
    <div class="span12 well white-box">
      <ul class="unstyled">
        <li><%= link_to "Matches",  matches_path,  class: 'item' %></li>
        <li><%= link_to "Cities", cities_path, class: 'item' %></li>
        <li><%= link_to "Teams",  teams_path,  class: 'item' %></li>
        <li><%= link_to "Stages", stages_path, class: 'item' %></li>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li class="dropdown">
          <a href="" class="brand dropdown-toggle" data-toggle="dropdown">
            É Gol <i class="icon-globe icon-white"></i>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to '<i class="icon-home"></i> Home'.html_safe, root_path %></li>
            <li><%= link_to '<i class="icon-question-sign"></i> Help'.html_safe, "#" %></li>
            <li><%= link_to '<i class="icon-info-sign"></i> About'.html_safe, "#" %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav hidden-phone">
        <li><%= link_to '<i class="icon-star icon-white"></i> Favorites'.html_safe, "#" %></li>
        <li><%= link_to '<i class="icon-calendar icon-white"></i> Calendar'.html_safe, "#" %></li>
        <li><%= link_to '<i class="icon-align-left icon-white"></i> Tree'.html_safe, "#" %></li>
        <% if signed_in? and current_user.admin? %>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-wrench icon-white"></i>
              Admin
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right">
              <li><%= link_to '<i class="icon-flag"></i> Matches'.html_safe, matches_path %></li>
              <li><%= link_to '<i class="icon-map-marker"></i> Cities'.html_safe, cities_path %></li>
              <li><%= link_to '<i class="icon-th"></i> Teams'.html_safe, teams_path %></li>
              <li><%= link_to '<i class="icon-time"></i> Stages'.html_safe, stages_path %></li>
              <li><%= link_to '<i class="icon-book"></i> Users'.html_safe, users_path %></li>
              <li><%= link_to '<i class="icon-ok-sign"></i> Sign in'.html_safe, signin_path %></li>
              <li><%= link_to '<i class="icon-exclamation-sign"></i> Sign up'.html_safe, signup_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav pull-right">
        <% if signed_in? %>
          <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-user icon-white"></i>
              <%= current_user.name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu pull-right">
              <li><%= link_to '<i class="icon-pencil"></i> Profile'.html_safe,  user_path(current_user) %></li>
              <li><%= link_to '<i class="icon-remove"></i> Sign out'.html_safe, signout_path, method: 'delete' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '<i class="icon-ok-sign icon-white"></i> Sign in'.html_safe, signin_path %></li>
          <li><%= link_to '<i class="icon-exclamation-sign icon-white"></i> Sign up now!'.html_safe, signup_path, class: "hidden-phone" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "É Gol!" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.7&key=AIzaSyBu4zQGNaajIn9VyiJeAoSDOYnTWbkbZtk&sensor=false" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <%= yield %>


</body>
</html>